services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - frontend

  frontend:
    build:
      context: ./web
    ports:
      - "3000:3000"
    env_file:
      - ./web/.env