services:
  server:
    build:
      context: .
    container_name: comment_server
    restart: always
    ports:
      - '5000:5000'
    env_file:
      - .env
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run start:prod
      "