services:
  db:
    image: postgres:15
    container_name: comment_pg
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: commentdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: .           
    container_name: comment_server
    restart: always
    ports:
      - '5000:5000'
    env_file:
      - .env              
    depends_on:
      - db
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run start:prod
      "

volumes:
  postgres_data: